# destination 'todos-out' is the rendezvous between the output and input channel
spring:
    cloud:
        stream:
            kafka:
                binder:
                    brokers: 'kafka.pks.kirklab.io'
            bindings:
                input:
                    destination: todos-out
